name: Build FIL - Windows (Qt 6.3.1)
on:
  workflow_call:
    secrets:
      qt_static_dec_key:
        description: 'MEGA decryption key for Qt static install archive URL'
        required: true
    outputs:
      qt_static_artifact_name:
        description: "FIL (Qt static) build artifact"
        value: ${{ jobs.build-fil.outputs.qt_static_artifact_name }}
env:
  qt_install_dir: ${{ github.workspace }}/Qt/Install
  qt_download_dir: ${{ github.workspace }}/Qt/Download
  fil_src_suffix: FIL/Source
  fil_src_dir: ${{ github.workspace }}/FIL/Source
  fil_build_dir: ${{ github.workspace }}/FIL/Build

jobs:
  build-fil:
    name: Build FIL - Windows (Release)
    strategy:
      matrix:
        qt_linkage: [static]
    runs-on: windows-latest
    env:
      vs_dir: C:/Program Files/Microsoft Visual Studio/2022/Enterprise
      cmake_gen: Ninja Multi-Config
    outputs:
      qt_static_artifact_name: ${{ steps.get_artifact_name.outputs.qt_static_artifact_name }}
    steps:
    - name: Set matrix derived variables
      uses: kanga333/variable-mapper@v0.2.2
      with:
        key: ${{ matrix.qt_linkage }}
        map: |
          {
            "static": {
              "qt_install_name": "qt-Production-6.3.1-win32-msvc-x64-static-release.7z",
              "qt_install_url": "https://mega.nz/file/QupBFJrC",
              "qt_install_url_key": "${{ secrets.qt_static_dec_key }}",
              "artifact_output_var": "qt_static_artifact_name"
            }
          }
        export_to: env,log
    - name: Set derived variables with shell because GitHub Actions env context sucks
      run: |
        echo "qt_install_dest=${{ env.qt_download_dir }}/${{ env.qt_install_name }}" >> $Env:GITHUB_ENV
        echo "fil_package_path=${{ env.fil_build_dir }}/out/dist" >> $Env:GITHUB_ENV
        $fil_install_path="${{ env.fil_build_dir }}/out/install"
        echo "fil_install_path=$fil_install_path" >> $Env:GITHUB_ENV
        echo "qt_cmake=${Env:qt_install_dir}/bin/qt-cmake.bat" >> $Env:GITHUB_ENV
    - name: Cache Qt Build
      id: cache-qt
      uses: actions/cache@v3
      with:
        path: ${{ env.qt_install_dir }}
        key: ${{ env.qt_install_name }}
    - name: Install megatools
      if: steps.cache-qt.outputs.cache-hit != 'true'
      run: choco install megatools
    - name: Create Qt Download Directory
      if: steps.cache-qt.outputs.cache-hit != 'true'
      run: New-Item -Path "${{ env.qt_download_dir }}" -ItemType "directory"
    - name: Download Qt Install
      if: steps.cache-qt.outputs.cache-hit != 'true'
      run: megatools dl "${Env:qt_install_url}#${Env:qt_install_url_key}" --path "${{ env.qt_download_dir }}"
    - name: Extract Qt Install
      if: steps.cache-qt.outputs.cache-hit != 'true'
      run: 7z x ${{ env.qt_install_dest }} -o${{ env.qt_install_dir }}
    - name: Checkout FIL
      uses: actions/checkout@v3
      with:
        path: ${{ env.fil_src_suffix }}
        fetch-depth: 0 # Required for verbose versioning to work correctly
    - name: Build/Install FIL
      working-directory: ${{ env.fil_src_dir }}
      shell: cmd
      run: |
        echo "Setup C++ Build Environment..."
        CALL "${{ env.vs_dir }}\Common7\Tools\VsDevCmd.bat" -arch=amd64
        echo "Configure CMake using Qt wrapper..."
        CALL "${{ env.qt_cmake }}" -G "${{ env.cmake_gen }}" -S "${{ env.fil_src_dir}}" -B "${{ env.fil_build_dir }}"  
        echo "Changing to build directory..."
        cd "%fil_build_dir%"
        echo "Building FIL release..."
        cmake --build . --target all --config Release
        echo "Installing FIL Release..."
        cmake --build . --target install --config Release
        echo "Packaging FIL..."
        cpack -C "Release"
        echo "Build complete."
    - name: Get FIL artifact name
      id: get_artifact_name
      run: echo "::set-output name=${{ env.artifact_output_var }}::$((Get-ChildItem -Path "${{ env.fil_package_path }}" -Filter *.zip)[0].BaseName)"
    - name: Upload FIL build artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.get_artifact_name.outputs[env.artifact_output_var] }}
        path: ${{ env.fil_install_path }}
        if-no-files-found: error
