name: Build Project
on:
  workflow_dispatch:
  push:
    branches-ignore:
    - 'master'
  workflow_run:
    workflows: Tag and Sync
    types: completed
    branches: dev
    # This is the branch that the original workflow ran on, which is technically dev, due to how
    # the "pull_request" trigger works (it works off master correctly for a merged PR but is triggered
    # by dev

# No GCC because it's not packaged for 20.04 or 22.04 yet
jobs:
  trigger-build:
    name: Build Project
    if: github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success'
    uses: oblivioncth/actions/.github/workflows/build-cxx-project.yml@v1
    secrets:
      ffynnon_access: ${{ secrets.OBYBOT_FFYNNON_ACCESS }}
    with:
      qt_version: 6.8.2
      runs_exclude: >
        [
            { "linkage": "shared" },
            { "compiler": "g++-10" },
            { "compiler": "g++-12" },
            { "compiler": "clang++-12" },
            { "compiler": "clang++-14" }
        ]
      runs_include: >
        [
            { "os": "ubuntu-22.04", "compiler": "clang++-18", "linkage": "static" },
            { "os": "ubuntu-24.04", "compiler": "clang++-18", "linkage": "static" },
            { "os": "ubuntu-24.04", "compiler": "g++-14", "linkage": "static" }
        ]
      pre_build_steps: |
        - name: Install Clang 18 [Linux]
          if: env.run_os == 'ubuntu-22.04' && env.run_compiler == 'clang++-18'
          shell: bash
          run: |
            wget https://apt.llvm.org/llvm.sh
            chmod u+x llvm.sh
            sudo ./llvm.sh 18

