name: OFILb Push Reaction
on:
  workflow_dispatch:
  push:
    branches-ignore:
    - 'master'

jobs:
  trigger-windows-build:
    name: Build OFILb (Windows)
    uses: ./.github/workflows/build-ofilb-windows.yml
    secrets:
      qt_static_dec_key: ${{ secrets.QT_WINDOWS_STATIC_DECRYPT_KEY }}